title: How the ICC Works
description: "The ICC is a court of last resort. See how certain cases get to the Court and how the legal process unfolds."
url: 'https://how-the-icc-works.aba-icc.org'
author: []
twitter:
  username: budparr
facebook:
  app_id: null
  publisher: null
  admins: null
logo: /assets/images/jekyll-white.svg
google_site_verification: null
github:
  username: budparr
owner: The New Dynamic
short_name: The Shortname
display: fullscreen
image_url: 'http://thenewdynamic.imgix.net'
google_analytics_id: UA-51919693-11
incremental: false
port: 3575
production: true
full_rebuild: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
destination: public
plugins_dir: ./_app/_plugins
layouts_dir: ./_app/_layouts
includes_dir: ./_app/_includes
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - node_modules
  - package.json
processes:
  - ''
  - jurisdictional-triggers
  - start-of-jurisdiction
  - preliminary-examination
  - investigation
  - arrest-warrant-and-summons
  - confirmation-of-charges
  - trial-and-appeal
  - sentencing-and-reparations
collections:
  cases:
    output: true
    permalink: '/:collection/:path/'
  introduction:
    output: false
    permalink: '/:collection/:path/'
    name: Introduction
    primary_section: true
    order: 0
  start-of-jurisdiction:
    output: false
    permalink: '/:collection/:path/'
    name: Start of Jurisdiction
    primary_section: true
    order: 1
    category: Referral to the ICC
  preliminary-examination:
    output: false
    permalink: '/:collection/:path/'
    name: Preliminary Examination
    primary_section: true
    order: 2
    category: Action by the ICC
  investigation:
    output: false
    permalink: '/:collection/#:path/'
    name: Investigation
    primary_section: true
    order: 3
  arrest-warrant-and-summons:
    output: false
    permalink: '/:collection/:path/'
    name: Arrest Warrant & Summons
    primary_section: true
    color: null
    order: 4
  confirmation-of-charges:
    output: false
    permalink: '/:collection/:path/'
    name: Confirmation of Charges
    primary_section: true
    order: 5
  trial-and-appeal:
    output: false
    permalink: '/:collection/:path/'
    name: Trial & Appeal
    primary_section: true
    order: 6
  sentencing-and-reparations:
    output: false
    permalink: '/:collection/:path/'
    name: Sentencing & Reparations
    primary_section: true
    order: 7
defaults:
  - scope:
      path: ''
    values:
      layout: page-single
  - scope:
      path: ''
      type: cases
    values:
      layout: cases
  - scope:
      path: ''
      type: referrals-and-communication
    values:
      layout: page-single
  - scope:
      path: ''
      type: preliminary-examination
    values:
      layout: page-single
  - scope:
      path: ''
      type: investigation
    values:
      layout: page-single
  - scope:
      path: ''
      type: arrest-warrant-and-summons
    values:
      layout: page-single
  - scope:
      path: ''
      type: confirmation-of-charges
    values:
      layout: page-single
  - scope:
      path: ''
      type: trial-and-appeal
    values:
      layout: page-single
  - scope:
      path: ''
      type: sentencing-and-reparations
    values:
      layout: page-single
  - scope:
      path: ''
      type: atrocity-crimes
    values:
      layout: page-single
