# jekyll-seo-tag
title: "How the ICC Works"
description: "The ICC is a court of last resort. It has to adhere to a great number of rules to determine where and when it can operate."
url: "https://how-the-icc-works.aba-icc.org" # the base hostname & protocol for your site
author: []
twitter:
  username: budparr
facebook:
  app_id:
  publisher:
  admins:
logo: /assets/images/jekyll-white.svg
google_site_verification:
github:
  username: budparr
owner: The New Dynamic
# manifest
short_name: The Shortname
display: fullscreen

# development meta data
image_url: http://thenewdynamic.imgix.net
google_analytics_id: UA-51919693-11
incremental: true
port: 3575

# Settings
production: true
full_rebuild: true
incremental: false
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
#source: src
destination: public
plugins_dir:  /_app/_plugins
layouts_dir:  /_app/_layouts
includes_dir: /_app/_includes


# CONTENT
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - node_modules
  - package.json

processes:
  - ''
  - jurisdictional-triggers
  - referrals-and-communication
  - preliminary-examination
  - investigation
  - arrest-warrant-and-summons
  - confirmation-of-charges
  - trial-and-appeal
  - sentencing-and-reparations


collections:
  cases:
    output: true
    permalink: '/:collection/:path/'
  introduction:
    output: false
    permalink: '/:collection/:path/'
    name: 'Introduction'
    primary_section: true
    order: 00
  referrals-and-communication:
    output: false
    permalink: '/:collection/:path/'
    name: 'Referrals and Communications'
    primary_section: true
    order: 01
    category: 'Referral to the ICC'
  preliminary-examination:
    output: false
    permalink: '/:collection/:path/'
    name: 'Preliminary Examination'
    primary_section: true
    order: 02
    category: 'Action by the ICC'
  investigation:
    output: false
    permalink: '/:collection/#:path/'
    name: 'Investigation'
    primary_section: true
    order: 03
  arrest-warrant-and-summons:
    output: false
    permalink: '/:collection/:path/'
    name: 'Arrest Warrant & Summons'
    primary_section: true
    color:
    order: 04
  confirmation-of-charges:
    output: false
    permalink: '/:collection/:path/'
    name: 'Confirmation of Charges'
    primary_section: true
    order: 05
  trial-and-appeal:
    output: false
    permalink: '/:collection/:path/'
    name: 'Trial & Appeal'
    primary_section: true
    order: 06
  sentencing-and-reparations:
    output: false
    permalink: '/:collection/:path/'
    name: 'Sentencing & Reparations'
    primary_section: true
    order: 07

defaults:
  - scope:
      path: ''
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'cases'
    values:
      layout: 'cases'
  - scope:
      path: ''
      type: 'referrals-and-communication'
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'preliminary-examination'
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'investigation'
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'arrest-warrant-and-summons'
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'confirmation-of-charges'
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'trial-and-appeal'
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'sentencing-and-reparations'
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'atrocity-crimes'
    values:
      layout: page-single
